### ISSUE TITLE
getKeyFromAddress() throws

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/ssb-ref#39]
https://github.com/fraction/oasis/issues/418

**Comment by austinfrey** [comment]
@christianbundy you are assigned to this bug. would you mind if I worked on it? I'm thinking we might only need to wrap `MultiServerAddress.decode(addr)` with a try/catch.

**Comment by christianbundy** [comment]
Yep, the 'assign' just means that I want it fixed and I don't want the stale[bot] to touch it!
